export const API_ENDPOINTS = {
  PUBLIC: {
    BRANDS: '/brands',
    VOUCHERS: '/vouchers',
    PRODUCTS: '/products',
    TRACE: '/trace',
    CATEGORIES: '/categories',
    SHOPS: '/shops',
    FLASH_SALES: '/flash-sales',
    BANNERS: '/banners',
    QUICK_LINKS: '/home/quick-links',
    SUPPLY_CHAIN_LOTS: '/supply-chain/lots',
    PAYMENT_GATEWAYS: '/payment-gateways',
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_ACCOUNT: '/auth/verify-account',
    SIMPLE_REGISTER: '/auth/simple-register',
    LOGOUT: '/auth/logout',
    VERIFY_EMAIL: '/auth/simple-verify',
    REFRESH_TOKEN: '/auth/refresh-token',
    FORGOT_PASSWORD: '/auth/forgot-password',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  USERS: {
    ME: '/users/me',
    AVATAR: '/users/me/avatar',
    ADDRESSES: '/users/addresses',
    VOUCHERS: '/users/vouchers',
    AFFILIATE_ACCOUNT: '/users/affiliate/account',
    AFFILIATE_WITHDRAWALS: '/users/affiliate/withdrawals',
    AFFILIATE_COMMISSIONS: '/users/affiliate/commissions',
    SUPPORT_TICKETS: '/users/support-tickets',
    DASHBOARD: '/users/dashboard',
    COMPLAINTS: '/users/complaints',
  },
  CART: {
    BASE: '/cart',
    COUNT: '/cart/count',
    ITEMS: '/cart/items',
    VALIDATE: '/cart/validate',
    SYNC_PRICES: '/cart/sync-prices',
    MERGE: '/cart/merge',
  },
  WISHLIST: {
    BASE: '/wishlist',
    COUNT: '/wishlist/count',
    CHECK: '/wishlist/check',
    MOVE_TO_CART: '/wishlist/move-to-cart',
  },
  SHIPPING: {
    PROVIDERS: '/shipping/providers',
    ESTIMATE_FEE: '/shipping/estimate-fee',
  },
  LOCATION: {
    PROVINCES: '/location/provinces',
    DISTRICTS: '/location/districts',
    WARDS: '/location/wards',
  },
  SELLER: {
    SHOP: '/seller/shop',
    SHOP_RESUBMIT: '/seller/shop/resubmit',
    SHOP_LOGO: '/seller/shop/logo',
    SHOP_BANNER: '/seller/shop/banner',
    SHOP_DOCUMENTS: '/seller/shop/documents',
    SHOP_POLICY: '/seller/shop/policy',
    SHOP_SUBSCRIPTION: '/seller/shop/subscription',
    SHOP_SUBSCRIPTION_HISTORY: '/seller/shop/subscriptions',
    SHOP_BANK_ACCOUNT: '/seller/shop/bank-account',
    PRODUCTS: '/seller/products',
    INVENTORY: '/seller/inventory',
    INVENTORY_LOW_STOCK_ALERTS: '/seller/inventory/alerts/low-stock',
    ORDERS: '/seller/orders',
    ORDERS_REVENUE: '/seller/orders/revenue',
    ORDERS_REFUNDS: '/seller/orders/refunds',
    ORDERS_PAYOUTS: '/seller/orders/payouts',
    ORDERS_B2B: '/seller/orders/b2b',
    ORDERS_B2B_REFUNDS: '/seller/orders/b2b/refunds',
    ORDERS_B2B_REVENUE: '/seller/orders/b2b/revenue',
    ORDERS_B2B_PAYOUTS: '/seller/orders/b2b/payouts',
    SHIPMENTS: '/seller/shipments',
    VOUCHERS: '/seller/vouchers',
    ATTRIBUTE_TEMPLATES: '/attribute-templates',
    QUOTATIONS: '/seller/quotations',
    REVIEWS: '/seller/reviews',
    SUPPLY_CHAIN_LOTS: '/seller/supply-chain/lots',
    FLASH_SALES: '/seller/flash-sales',
    DASHBOARD: '/seller/dashboard',
    CHAT_ROOMS: '/seller/chat/rooms',
  },
  ADMIN: {
    BLOG: '/admin/blog',
    TAGS: '/admin/blog/tags',
    AUDIT_LOGS: '/admin/audit-logs',
    USERS: '/admin/users',
    SHOPS: '/admin/shops',
    SUBSCRIPTION_PLANS: '/admin/subscription-plans',
    CATEGORIES: '/admin/categories',
    PRODUCTS: '/admin/products',
    INVENTORY: '/admin/inventory',
    INVENTORY_LOW_STOCK_ALERTS: '/admin/inventory/alerts/low-stock',
    ORDERS: '/admin/orders',
    ORDERS_DASHBOARD: '/admin/orders/dashboard',
    REFUNDS: '/admin/refunds',
    PAYOUTS: '/admin/payouts',
    BANNERS: '/admin/banners',
    QUICK_LINKS: '/admin/quick-links',
    LOCATION_IMPORT: '/admin/location/import',
    SHIPPING_PROVIDERS: '/admin/shipping/providers',
    VOUCHERS: '/admin/vouchers',
    BRANDS: '/admin/brands',
    AFFILIATE_WITHDRAWALS: '/admin/affiliate/withdrawals',
    REVIEWS: '/admin/reviews',
    CONTENT_FLAGS: '/admin/content-flags',
    SUPPORT_TICKETS: '/admin/support-tickets',
    PAYMENT_GATEWAYS: '/admin/payment-gateways',
    POLICIES: '/admin/policies',
    NEWSLETTER: '/admin/newsletter',
    LOYALTY: '/admin/loyalty/accounts',
    FLASH_SALES: '/admin/flash-sales',
    DASHBOARD: '/admin/dashboard',
    COMPLAINTS: '/admin/complaints',
  },
  STAFF: {
    ME_PROFILE: '/staff/me/profile',
  },
  ROLES: '/roles',
  PERMISSIONS: '/permissions',
  QUOTATIONS: '/quotations',
  REVIEWS: '/reviews',
  POLICIES: '/policies',
  ORDERS: '/orders',
  ORDERS_B2B: '/my/orders/b2b',
  NOTIFICATIONS: '/notifications',
  NEWSLETTER: '/newsletter',
  LOYALTY: '/loyalty',
  CHAT: {
    ROOMS: '/chat/rooms',
  },
  WEBHOOKS: {
    PAYMENT: '/webhooks/payment',
  },
  CHECKOUT: {
    CUSTOM: '/checkout/custom',
  },
} as const;

export type ApiEndpoints = typeof API_ENDPOINTS;
